#!/usr/bin/env python3
"""Generate an App Module from an Upstream ct/<app>.sh.

An App Module has the same inputs as the generic lxc module, with the resource
values and container requirements of one App as defaults. Those values are the
`var_*` lines of the Upstream script, which is the only part of Upstream regular
enough to read mechanically.

    scripts/generate_app_module.py --upstream ../ProxmoxVE caddy
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERIC = ROOT / "terraform" / "modules" / "lxc"
APPS = ROOT / "terraform" / "apps"

VAR_LINE = re.compile(r'^\s*var_([a-z0-9_]+)="\$\{var_\1:-([^}]*)\}"', re.MULTILINE)
VARIABLE_BLOCK = re.compile(r'^variable "(\w+)" \{\n(.*?)^\}\n', re.MULTILINE | re.DOTALL)
DEFAULT_LINE = re.compile(r"^  default\s*=.*$", re.MULTILINE)

# Upstream values this module has no input for. `version` is the OS release,
# which the caller expresses through os_template; `arm64` says the script also
# runs on ARM. `gpu` asks for devices that Upstream detects on the host.
NOT_MAPPED = {"version", "arm64"}
NEEDS_DEVICES = {"gpu"}


def flag(value):
    return "true" if value in ("1", "yes") else "false"


def quoted(value):
    return f'"{value}"'


def tag_list(value):
    return "[" + ", ".join(quoted(tag) for tag in value.split(";") if tag) + "]"


# Upstream name -> (input of the lxc module, how to write the value in HCL)
MAPPING = {
    "cpu": ("cpu_cores", str),
    "ram": ("memory", str),
    "disk": ("disk_size", str),
    "os": ("os_type", quoted),
    "tags": ("tags", tag_list),
    "unprivileged": ("unprivileged", flag),
    "nesting": ("nesting", flag),
    "keyctl": ("keyctl", flag),
    "fuse": ("fuse", flag),
    "mknod": ("mknod", flag),
    "tun": ("tun", flag),
}


def upstream_values(script):
    """The var_* defaults of a script. Where a script sets a value once per OS,
    the Debian branch comes last and wins."""
    values = dict(VAR_LINE.findall(script))
    if values.setdefault("os", "debian") != "debian":
        sys.exit(f"Upstream runs this App on {values['os']}; only Debian is translated.")
    return values


def defaults_for(app, values):
    defaults = {"hostname": quoted(app)}
    notes = []
    for name, value in values.items():
        if name in MAPPING:
            target, render = MAPPING[name]
            defaults[target] = render(value)
        elif name in NEEDS_DEVICES:
            notes.append(f"Upstream sets var_{name}={value}: pass the devices in through `devices`.")
        elif name not in NOT_MAPPED:
            sys.exit(f"var_{name} has no mapping yet; add it to MAPPING or NOT_MAPPED.")
    return defaults, notes


def with_default(name, body, value):
    line = f"  default = {value}"
    if DEFAULT_LINE.search(body):
        body = DEFAULT_LINE.sub(line, body, count=1)
    else:
        body += line + "\n"
    return f'variable "{name}" {{\n{body}}}\n'


def commit_of(repo):
    return subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("app", help="Upstream script name, e.g. caddy")
    parser.add_argument("--upstream", required=True, type=Path, help="checkout of community-scripts/ProxmoxVE")
    args = parser.parse_args()

    source = args.upstream / "ct" / f"{args.app}.sh"
    if not source.is_file():
        sys.exit(f"{source} does not exist.")

    values = upstream_values(source.read_text())
    defaults, notes = defaults_for(args.app, values)

    header = (
        f"# Generated by scripts/generate_app_module.py from ct/{args.app}.sh at\n"
        f"# community-scripts/ProxmoxVE@{commit_of(args.upstream)}. Do not edit.\n"
    )
    header += "".join(f"#\n# {note}\n" for note in notes)

    generic = (GENERIC / "variables.tf").read_text()
    names = [name for name, _ in VARIABLE_BLOCK.findall(generic)]
    variables = VARIABLE_BLOCK.sub(
        lambda block: with_default(block[1], block[2], defaults[block[1]])
        if block[1] in defaults
        else block[0],
        generic,
    )

    arguments = "\n".join(f"  {name} = var.{name}" for name in names)
    main_tf = f'module "lxc" {{\n  source = "../../modules/lxc"\n\n{arguments}\n}}\n'

    outputs = (
        'output "vm_id" {\n  value = module.lxc.vm_id\n}\n\n'
        'output "ipv4_address" {\n  value = module.lxc.ipv4_address\n}\n'
    )

    target = APPS / args.app
    target.mkdir(parents=True, exist_ok=True)
    (target / "variables.tf").write_text(header + "\n" + variables)
    (target / "main.tf").write_text(header + "\n" + main_tf)
    (target / "outputs.tf").write_text(header + "\n" + outputs)
    (target / "versions.tf").write_text(header + "\n" + (GENERIC / "versions.tf").read_text())
    subprocess.run(["terraform", "fmt", str(target)], check=True, stdout=subprocess.DEVNULL)
    print(f"Wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
