# Generated by scripts/generate_app_module.py from ct/caddy.sh at
# community-scripts/ProxmoxVE@ea59019670202b740b4bd11c03f6ab4e746cc46f. Do not edit.

module "lxc" {
  source = "../../modules/lxc"

  node_name           = var.node_name
  vm_id               = var.vm_id
  hostname            = var.hostname
  description         = var.description
  tags                = var.tags
  os_template         = var.os_template
  os_type             = var.os_type
  cpu_cores           = var.cpu_cores
  memory              = var.memory
  swap                = var.swap
  disk_size           = var.disk_size
  datastore_id        = var.datastore_id
  mount_points        = var.mount_points
  bridge              = var.bridge
  vlan_id             = var.vlan_id
  mac_address         = var.mac_address
  mtu                 = var.mtu
  firewall            = var.firewall
  ipv4_address        = var.ipv4_address
  ipv4_gateway        = var.ipv4_gateway
  ipv6_address        = var.ipv6_address
  ipv6_gateway        = var.ipv6_gateway
  dns_servers         = var.dns_servers
  dns_search_domain   = var.dns_search_domain
  ssh_authorized_keys = var.ssh_authorized_keys
  unprivileged        = var.unprivileged
  start_on_boot       = var.start_on_boot
  protection          = var.protection
  nesting             = var.nesting
  keyctl              = var.keyctl
  fuse                = var.fuse
  mknod               = var.mknod
  mount_fs            = var.mount_fs
  tun                 = var.tun
  devices             = var.devices
}
