# Generated by scripts/generate_app_module.py from ct/caddy.sh at
# community-scripts/ProxmoxVE@ea59019670202b740b4bd11c03f6ab4e746cc46f. Do not edit.

output "vm_id" {
  value = module.lxc.vm_id
}

output "ipv4_address" {
  value = module.lxc.ipv4_address
}
