# Generated by scripts/generate_app_module.py from ct/caddy.sh at
# community-scripts/ProxmoxVE@ea59019670202b740b4bd11c03f6ab4e746cc46f. Do not edit.

terraform {
  required_version = ">= 1.7"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = ">= 0.114"
    }
  }
}
